# Generated by Django 6.0.2 on 2026-02-23 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_newslettersubscriber_is_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='is_confirmed',
        ),
    ]
