# Generated by Django 6.0.2 on 2026-03-30 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_review_options_alter_review_comment_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderitem',
            name='products_or_order_i_7f4974_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='products_or_product_8b49c6_idx',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
    ]
